### PR TITLE
Process Initial MSP messages in the correct order.

### PR DESCRIPTION
**Pull request by geoffsim**
On startup, the initial MSP_VARIANT message MUST be processed before the MSP_VTX_CONFIG message.
If this does not happen, the VTX will/may not register properly with the FC and potentially discard further MSP messages.
This change will ensure the initial messages are processed in order.
Process Initial MSP messages in the correct order.

### CODE REVIEW

**Comment by nerdCopter** [comment]
Upon merge, this was GitHub actions build number 418. At this build, my Race V3 no longer outputs signal.  Build 417 still works.  Running EmuFlight on this quad, but i don't think it matters.

**Comment by geoffsim** [comment]
More information please. What do the build numbers refer to?

________________________________

**Comment by nerdCopter** [comment]
```
Merge pull request #222 from geoffsim/VTX-Config-Processing
hdzero-vtx build #418: Commit 544f87e pushed by ligenxxxx 
```
https://github.com/hd-zero/hdzero-vtx/actions/runs/11662675049

**Comment by geoffsim** [comment]
Perhaps you could try the head of the VTX source code and let me know the results.
As I don't know EmuFlight, I don't know what the MSP contract is between EmuFlight and the VTX.
I have tested my changes against iNav and BetaFlight and they work as expected.
Betaflight requires a V1 MSP_CONFIG message to be sent continuously to the FC.
It might be that EmuFlight is using the same message flow as BetaFlight.

Contact me on Discord (geoffsim) and I can send you an updated VTX firmware to test.
(assuming EmuFlight responds to an MSP_FC_VARIANT request of "EMUF" ?)

Failing that, I will have to look into EmuFlight for testing purposes.

Geoff.

________________________________

**Comment by nerdCopter** [comment]
All aforementioned personal issues solved by #231

**Pull request merged**
