### PR TITLE
if dm6300 lost, led will fast flash 2 times every second.

### PR DESCRIPTION
**Pull request by ligenxxxx**
Need to test

### CODE REVIEW

**Comment by HazzaHFPV** [comment]
I've tested v1.5.0-RC1 where this was implemented. I noticed that on both my Whoop_Lite and my Freestyle V1 VTX the blue light will flash 2 times fast every second. However, both vtx seem to work fine.
Only thing I noticed on the whoop lite is, that I seem to get more sparkles when on 200mW, not sure if that is to do with this release but I think it was better/more stabl image on v1.4.0. Also, 1080p30 seems a little more fuzzy than previously, but that might be the new 9.3.0-RC1 on the goggles, which I am also running.

**Comment by QiNFPV** [comment]
After I switch the Freestyle V2 into 560/60FPS mode. The vtx failed to reboot and can't be found anymore. The blue LED flashes 2times/s. Try reflashing the firmware, and didn't work...

**Comment by evilC** [comment]
What is "dm6300 lost"? A quick google tells me that the DM6300 is one of the ASICs or something? Is this maybe the BGA chip which is prone to issues?

**Comment by QiNFPV** [comment]
Switched to narrow bandwidth and everything works



发自我的iPhone


------------------ Original ------------------
From: Clive Galway ***@***.***&gt;
Date: Wed,Nov 1,2023 11:35 PM
To: hd-zero/hdzero-vtx ***@***.***&gt;
Cc: QiNFPV ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [hd-zero/hdzero-vtx] if dm6300 lost, led will fast flash 2 timesevery second. (PR #166)





 
What is "dm6300 lost"? A quick google tells me that the DM6300 is one of the ASICs or something? Is this maybe the BGA chip which is prone to issues?

**Comment by ligenxxxx** [comment]
I have fixed this issue at #170.

**Pull request merged**
