### PR TITLE
Betaflight HD OSD support

### PR DESCRIPTION
**Pull request by ligenxxxx**

### CODE REVIEW

**Comment by ligenxxxx** [comment]
Also to update VRX/goggle FW.

**Comment by bkleiner** [comment]
i have understood it as such that the `MSP_GET_OSD_CANVAS` (id 189) is supposed to be only sent by the configurator and `MSP_SET_OSD_CANVAS` (id 188) is supposed to be sent by the vtx.
I don't know if betaflight exposes a functionality for the user to set the resolution manually, from my conversation with someone involved in the creation for this spec, i dont think so.

**Comment by ligenxxxx** [comment]
> i have understood it as such that the `MSP_GET_OSD_CANVAS` (id 189) is supposed [to be only sent by the configurator](https://github.com/betaflight/betaflight/blob/master/docs/API/DisplayPort.md) and `MSP_SET_OSD_CANVAS` (id 188) is supposed to be sent by the vtx. I don't know if betaflight exposes a functionality for the user to set the resolution manually, from my conversation with someone involved in the creation for this spec, i dont think so.

In the latest betaflight configurator, OSD format has added HD format which defaults to 53x20.
**MSP_SET_OSD_CANVAS** is only for the convenience of VTX to set the resolution when it is not compatible with 53x20. As a user, you don't need to care about this.

**Comment by SteveCEvans** [comment]
As per the comments above the code is currently handling `MSP_CMD_GET_OSD_CANVAS` which isn’t what’s intended. The FC won’t query the VTX for the canvas size; it’s expecting the VTX to declare it on startup, or whenever the canvas size is changed in the goggles (which you may or may not support).

**Comment by ligenxxxx** [comment]
@SteveCEvans  HDZero only supports 53x20 canvas size, which is the betaflight default setting. This is what I want.

**Comment by howels** [comment]
> @SteveCEvans HDZero only supports 53x20 canvas size, which is the betaflight default setting. This is what I want.

`MSP_CMD_GET_OSD_CANVAS` is supposed to be used by the configurator, VTX should send `MSP_CMD_SET_OSD_CANVAS`  as described in https://github.com/betaflight/betaflight/blob/608aff9a7638f05f1caced2c6fa0b5ff04c68652/docs/API/DisplayPort.md#msp_set_osd_canvas
This way HDzero ensures that it expresses the desired resolution, even if defaults change later.

**Comment by SteveCEvans** [comment]
Agreed. Please see https://github.com/betaflight/betaflight/blob/master/docs/API/DisplayPort.md.

The VTX sends the `MSP_SET_OSD_CANVAS` command to the FC to inform it of the canvas size. It should not be sending the`MSP_OSD_CANVAS` query. Only the configurator will do that.

**Pull request merged**
