### PR TITLE
Fix BetaFlight Issues

### PR DESCRIPTION
**Pull request by geoffsim**
Ensure MSP requests to BF include MSP_GET_CONFIG command.
Change reported power levels to include 0mW.

Tested on BF and iNav.

### CODE REVIEW

**Comment by nerdCopter** [comment]
upon merge, this was GitHub action build 426. Build 426 causes immediate rainbow on freestyle v2 using EmuFlight 0.4.3. Unknown if flightware is a factor. Github build 424 works fine AFAICT.

**Comment by geoffsim** [comment]
EmuFlight was not tested. Perhaps it expects continuous CONFIG messages like BF does.
When you say rainbow, do you mean no transmission?
Can you access the VTX menu?
What are these build numbers you are using?

________________________________

**Comment by nerdCopter** [comment]
By "rainbow", i had about 2 seconds of signal, then signal loss. menu not tested. 
Reflashed same build today and could not reproduce rainbow, but instead now have no signal whatsoever. (Similar to other comment on PR #221)

EmuFlight ignores Any VTX-table and/or channel/band MSP (ignores MSP command 227 & 228). Only OSD is supported.  INav's https://github.com/iNavFlight/inav/pull/7668 was ported here: https://github.com/emuflight/EmuFlight/pull/775 (and slightly modified afterward; unrelated)

failing HDZero build info:
```
Merge pull request #229 from geoffsim/VTX-Config-BF
hdzero-vtx build #426: Commit 8f7da85 pushed by [ligenxxxx](https://github.com/ligenxxxx)
```
https://github.com/hd-zero/hdzero-vtx/actions/runs/12028231802



Build 424 works (on Freestyle v2, not Race V3):
```
Merge pull request #228 from ligenxxxx/Restore-common.h
hdzero-vtx build #424: Commit 6aa7a61 pushed by ligenxxxx 
```
https://github.com/hd-zero/hdzero-vtx/actions/runs/11904414442

**Comment by nerdCopter** [comment]
I was able to receive EmuFlight OSD, but it had strong delay and difficult to navigate. practically unresponsive.  No camera feed with stated Build 426.

**Comment by nerdCopter** [comment]
i cannot rule out some other issue.  reverted to build 424 and then build 418 because no signal. then when i re-scanned, somehow the VTX was set to R4 and 25mW.
Kind of tired of testing when my intention is to go out and fly.

**Comment by nerdCopter** [comment]
apologies for all the commenting noise. tried `main` @`HEAD`, no VTX signal even with channel-scan. reverted to build 424 with proper configured VTX as seems to be the last working build (for my freestyle v2).

**Comment by nerdCopter** [comment]
All aforementioned personal issues solved by #231

**Pull request merged**
