### PR TITLE
Overhaul VTX_CONFIG processing.

### PR DESCRIPTION
**Pull request by geoffsim**
Initial VTX_CONFIG from the FC will write any diffrerences to EEPROM to ensure FC and VTX are in sync.
The whole VTX_CONFIG processing for V1 and V2 messages has been overhauled to ensure the FC and VTX are always (!) in sync regardless of what VTX menu is used to change settings.

### CODE REVIEW

**Comment by geoffsim** [comment]
Note that PIT mode is not working properly and is the subject of another PR I am working on.

**Comment by KissUltra** [comment]
Hi!

I DO NOT respond to VTX_CONFIG command (fc id is ULTR). This change breaks stick processing from ultra. VTX keeps polling 88 forever. That makes impossible to configure VTX from stick commands on v1.71.

Having VTX awareness of what FC its connected to is a bad design choice in general. 
Alex (KissUltra)

**Comment by geoffsim** [comment]
As this PR is over a year old and merged, you will need to post a new issue and wait for it to be looked at. Alternatively, you could fix the issue yourself (making sure you don't break support for the other FCs) and post a PR. It should not be too difficult to ignore the config synchronisation for your FC.

AFAIC the VTX firmware needs rewriting as it has become difficult to maintain due to a myriad of fixes and updates. I wanted to have a go at this but undocumented and proprietary libraries along with a lack of documentation in general made that impossible.

**Comment by ligenxxxx** [comment]
@KissUltra 
https://github.com/hd-zero/hdzero-vtx/actions/runs/20061791002
Please this firmware.

**Comment by KissUltra** [comment]
Works!

Thank you Ligen! You are the best!

Fedor Commander

**Pull request merged**
