### PR TITLE
msp: send canvas size

### PR DESCRIPTION
**Pull request by bkleiner**
implement new msp command to sync canvas size
https://github.com/betaflight/betaflight/blob/master/docs/API/DisplayPort.md#msp_set_osd_canvas
_widly_ untested

### CODE REVIEW

**Comment by howels** [comment]
FYI this should work with Betaflight 4.4 RC0 builds, user can select both MSP-VTX features and then the HD OSD option will allow the VTX to tell the FC what OSD grid size it wants to use.

**Comment by ligenxxxx** [comment]
Currently, the only thing that may be modified in the resolution is that the FC sends the HD_5018 or HD_3016 resolution to the VTX.
For general FC, VTX osd works with SD_3016 by default. This has worked fine in the past.
Recently betaflight added HD OSD protocol. My idea is to add support for betaflight HD OSD without affecting previous functionality.
VTX needs to communicate with FC to obtain whether FC can support HD OSD, and then VTX sets FC and its own osd resolution.

**Comment by howels** [comment]
> Currently, the only thing that may be modified in the resolution is that the FC sends the HD_5018 or HD_3016 resolution to the VTX. For general FC, VTX osd works with SD_3016 by default. This has worked fine in the past. Recently betaflight added HD OSD protocol. My idea is to add support for betaflight HD OSD without affecting previous functionality. VTX needs to communicate with FC to obtain whether FC can support HD OSD, and then VTX sets FC and its own osd resolution.

This can be done by querying MSP for FC identifier "BTFL" and MSP version  is major version 1 and minor version 45 or greater.

**Comment by bkleiner** [comment]
> > Currently, the only thing that may be modified in the resolution is that the FC sends the HD_5018 or HD_3016 resolution to the VTX. For general FC, VTX osd works with SD_3016 by default. This has worked fine in the past. Recently betaflight added HD OSD protocol. My idea is to add support for betaflight HD OSD without affecting previous functionality. VTX needs to communicate with FC to obtain whether FC can support HD OSD, and then VTX sets FC and its own osd resolution.
> 
> This can be done by querying MSP for FC identifier "BTFL" and MSP version is major version 1 and minor version 45 or greater.

tbh, i think we should try to avoid that if at all possible, as it that would probably be specific to BF.
in my mind it would be preferable if we find a solution that is compatible with any firmware that chooses to implement this new api.
i am hoping that we can get away with sending out `MSP_SET_OSD_CANVAS` cmd with the 5018 resolution, waiting for the response and only actually switching it if the response is not an error.
any sane msp implementation should answer to unknown command with an error, so it should be backwards compatible.

**Comment by howels** [comment]
> > > Currently, the only thing that may be modified in the resolution is that the FC sends the HD_5018 or HD_3016 resolution to the VTX. For general FC, VTX osd works with SD_3016 by default. This has worked fine in the past. Recently betaflight added HD OSD protocol. My idea is to add support for betaflight HD OSD without affecting previous functionality. VTX needs to communicate with FC to obtain whether FC can support HD OSD, and then VTX sets FC and its own osd resolution.
> > 
> > 
> > This can be done by querying MSP for FC identifier "BTFL" and MSP version is major version 1 and minor version 45 or greater.
> 
> tbh, i think we should try to avoid that if at all possible, as it that would probably be specific to BF. in my mind it would be preferable if we find a solution that is compatible with any firmware that chooses to implement this new api. i am hoping that we can get away with sending out `MSP_SET_OSD_CANVAS` cmd with the 5018 resolution, waiting for the response and only actually switching it if the response is not an error. any sane msp implementation should answer to unknown command with an error, so it should be backwards compatible.

Makes sense, sounds good in principle. Minimal code required.

**Comment by ligenxxxx** [comment]
> > > Currently, the only thing that may be modified in the resolution is that the FC sends the HD_5018 or HD_3016 resolution to the VTX. For general FC, VTX osd works with SD_3016 by default. This has worked fine in the past. Recently betaflight added HD OSD protocol. My idea is to add support for betaflight HD OSD without affecting previous functionality. VTX needs to communicate with FC to obtain whether FC can support HD OSD, and then VTX sets FC and its own osd resolution.
> > 
> > 
> > This can be done by querying MSP for FC identifier "BTFL" and MSP version is major version 1 and minor version 45 or greater.
> 
> tbh, i think we should try to avoid that if at all possible, as it that would probably be specific to BF. in my mind it would be preferable if we find a solution that is compatible with any firmware that chooses to implement this new api. i am hoping that we can get away with sending out `MSP_SET_OSD_CANVAS` cmd with the 5018 resolution, waiting for the response and only actually switching it if the response is not an error. any sane msp implementation should answer to unknown command with an error, so it should be backwards compatible.

- Recognize BTFL by **FC_VARIANT**, just to avoid some FC not working with msp cmd 0xBD.
- Detect whether the user has enabled HD OSD through **MSP_GET_OSD_CANVAS** (0xBD).
- I plan to support 53x20 osd layout, add this new osd resolution.
- The analysis of HD OSD and SD OSD seem to have few cars, maybe only need to modify the buffer size.

**Comment by sugaarK** [comment]
> * The analysis of HD OSD and SD OSD seem to have few cars, maybe only need to modify the buffer size.

We can also slow down some of the elements that don’t need to be rapidly updated if we need to @ligenxxxx  our osd manages and redraws elements individually so slowing stuff down to save bandwidth is pretty easy

**Comment by howels** [comment]
@ligenxxxx do you have code available to test this? We are going through RC phase on Betaflight 4.4 which adds this ability to switch to specific VTX-defined HD modes when VTX tells FC it wants to use HD. Would very much like to validate HDzero as others are already compatible.

**Comment by bkleiner** [comment]
see https://github.com/hd-zero/hdzero-vtx/pull/72 
binaries to test are built via https://github.com/hd-zero/hdzero-vtx/actions

**Pull request closed without merging**
