### PR TITLE
EMUF fc variant support

### PR DESCRIPTION
**Pull request by nerdCopter**
* uncertain since the original did not match the sorting order of the goggles `osd.c`.
* please see https://github.com/hd-zero/hdzero-goggle/pull/371#issuecomment-1839134332

please feedback

### CODE REVIEW

**Comment by ligenxxxx** [comment]
Don't worry, VTX actually transmits the complete 4 variant characters to VRX/Goggle.
As long as the characters are able it will work fine.
A long time ago, we used the agreed index to transmit FC variant in order to save the cost of data volume. But this will bring a problem. When a new FC system appears, we need to maintain it specially, which is very troublesome. So we decided to address this concern by transmitting the complete 4 characters.

**Comment by ligenxxxx** [comment]
Even if you don't modify it on the VTX side, I believe OSD can work correctly on goggle, but I hope that the definition of fc_variant between goggle and vtx can correspond, which at least seems comfortable.

**Comment by nerdCopter** [comment]
thanks for reply.  I've compiled and tested this PR, but it does not select/apply my custom `EMUF_000.bmp`.
It still reverts to ARDU, so i'm forced to name it `ARDU_000.bmp` :(

**Comment by ligenxxxx** [comment]
image
Please print fc_variant here in goggle, so that we can know whether the problem occurs in VTX or Goggle.

**Comment by nerdCopter** [comment]
Closing this VTX PR. 
Found the EmuFlight code that sent `ARDU` (to be repaired).
Goggles PR seems good.

**Pull request closed without merging**
